package guru.sfg.beer.order.service.web.model;

/**
 * Created by BECHRAOUI, 22/10/2020
 */
public enum BeerOrderEventEnum {
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED, ALLOCATION_SUCCESS,
    ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED, BEERORDER_PICKED_UP
}
